In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_table('C:/Users/Bhavya Popli/Desktop/datasets/poker-hand/train.txt', header=None,sep=',')
train.head()

   0   1   2   3   4   5   6   7   8   9   10
0   1  10   1  11   1  13   1  12   1   1   9
1   2  11   2  13   2  10   2  12   2   1   9
2   3  12   3  11   3  13   3  10   3   1   9
3   4  10   4  11   4   1   4  13   4  12   9
4   4   1   4  13   4  12   4  11   4  10   9

In [3]:
test = pd.read_table('C:/Users/Bhavya Popli/Desktop/datasets/poker-hand/test.txt', header=None,sep=',')
test.head()

   0   1   2   3   4   5   6   7   8   9   10
0   1   1   1  13   2   4   2   3   1  12   0
1   3  12   3   2   3  11   4   5   2   5   1
2   1   9   4   6   1   4   3   2   3   9   1
3   1   4   3  13   2  13   2   1   3   6   1
4   3  10   2   7   1   2   2  11   4   9   0

In [4]:
train.dropna()

       0   1   2   3   4   5   6   7   8   9   10
0       1  10   1  11   1  13   1  12   1   1   9
1       2  11   2  13   2  10   2  12   2   1   9
2       3  12   3  11   3  13   3  10   3   1   9
3       4  10   4  11   4   1   4  13   4  12   9
4       4   1   4  13   4  12   4  11   4  10   9
5       1   2   1   4   1   5   1   3   1   6   8
6       1   9   1  12   1  10   1  11   1  13   8
7       2   1   2   2   2   3   2   4   2   5   8
8       3   5   3   6   3   9   3   7   3   8   8
9       4   1   4   4   4   2   4   3   4   5   8
10      1   1   2   1   3   9   1   5   2   3   1
11      2   6   2   1   4  13   2   4   4   9   0
12      1  10   4   6   1   2   1   1   3   8   0
13      2  13   2   1   4   4   1   5   2  11   0
14      3   8   4  12   3   9   4   2   3   2   1
15      1   3   4   7   1   5   2   4   4  13   0
16      1   4   1   1   1   3   3   5   3   2   4
17      3   8   3  12   2   7   2   6   1   2   0
18      4   8   1  11   4   6   3   2   4  12   0
19      3   7   2   7   4  11   1  12   3   1   1
20      1  13   4   8   2   7   2  10   3  13   1
21      2   6   2   8   1  11   1   4   3   7   0
22      3  10   2  10   4   5   1   2   3   8   1
23      2   1   3  13   4   6   1   9   4   1   1
24      2  10   2   8   1   8   3   2   2  13   1
25      2  13   1   5   4   5   4   8   3   3   1
26      3   1   1   5   2   7   3  13   1   1   1
27      1   7   1   5   4   8   1   6   2   6   1
28      3   7   3   9   2  12   2   5   4   4   0
29      2  10   1   1   1  12   4   6   2   8   0
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
24980   4   5   4  13   3  10   1  13   3   2   1
24981   3   3   1  11   4   2   3   6   3   9   0
24982   4   1   2   1   1   3   2   6   3   1   3
24983   3   2   3   1   4  10   4   6   1   3   0
24984   2   9   3   1   4   5   2   6   3  10   0
24985   3  10   1   5   3   3   4   3   4   2   1
24986   2   8   2   5   1  11   4   1   1  12   0
24987   2  12   3   9   1   4   3   7   4   3   0
24988   4   8   1   8   1   4   3   3   4  12   1
24989   4  11   3   2   2  13   4   6   4  12   0
24990   4  10   2  11   2   9   4   5   1   8   0
24991   2  11   2   9   4   9   4   6   2  10   1
24992   4   6   4  10   1   1   1   4   1   3   0
24993   2   6   2  13   2   5   4   3   2  11   0
24994   4   7   1  10   2   6   1  11   3   7   1
24995   2  12   1   2   4   8   3   3   4   6   0
24996   2  11   1   5   1  10   4  10   2  13   1
24997   3   7   3  13   2   4   1  12   3   8   0
24998   1   8   4   1   4  12   1  13   1  10   0
24999   4  12   3  11   4   4   3  12   2  12   3
25000   2   8   2  12   4   3   4   2   4   4   0
25001   2  12   3   5   3   8   4   1   4   2   0
25002   4  10   2  13   4   5   4   7   1   5   1
25003   1  12   2   9   2  12   4   8   1  13   1
25004   3   5   3   7   4  11   3  11   3   2   1
25005   3   9   2   6   4  11   4  12   2   4   0
25006   4   1   4  10   3  13   3   4   1  10   1
25007   2   1   2  10   4   4   4   1   4  13   1
25008   2  12   4   3   1  10   1  12   4   9   1
25009   1   7   3  11   3   3   4   8   3   7   1

[25010 rows x 11 columns]

In [5]:
test.dropna()

        0   1   2   3   4   5   6   7   8   9   10
0        1   1   1  13   2   4   2   3   1  12   0
1        3  12   3   2   3  11   4   5   2   5   1
2        1   9   4   6   1   4   3   2   3   9   1
3        1   4   3  13   2  13   2   1   3   6   1
4        3  10   2   7   1   2   2  11   4   9   0
5        1   3   4   5   3   4   1  12   4   6   0
6        2   6   4  11   2   3   4   9   1   7   0
7        3   2   4   9   3   7   4   3   4   5   0
8        4   4   3  13   1   8   3   9   3  10   0
9        1   9   3   8   4   4   1   7   3   5   0
10       4   7   3  12   1  13   1   9   2   6   0
11       2  12   1   3   2  11   2   7   4   8   0
12       4   2   2   9   2   7   1   5   3  11   0
13       1  13   2   6   1   6   2  11   3   5   1
14       3   8   2   7   1   9   3   6   2   3   0
15       2  10   1  11   1   9   3   1   1  13   0
16       4   2   4  12   2  12   2   7   3  10   1
17       4   5   2   2   4   9   1   5   4   1   1
18       2   3   3   9   2   1   2   6   4  10   0
19       1   7   2  11   4   1   2   9   3  13   0
20       4  12   1   6   3   1   2   2   1   8   0
21       2   5   3   1   3  13   4  13   3   8   1
22       1   3   4   8   2   1   1  12   3   5   0
23       2   8   4   6   1  12   2  13   1   8   1
24       1   7   4  13   4   9   1   9   1  10   1
25       2  13   3   3   2  11   2   6   1   4   0
26       4   3   2   4   4   9   2   8   1  11   0
27       2   5   3   7   2  12   3   3   2  11   0
28       3   4   2   1   3  10   1   8   4   1   1
29       4  11   2  13   4   4   3   8   4   1   0
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
999970   3   8   3  13   3   3   2   7   1  10   0
999971   4   2   1  12   2  12   4  11   2   9   1
999972   4   3   2   4   2   8   1   6   4  11   0
999973   3   7   4   9   3   6   3  12   2  11   0
999974   2   6   4   3   2   1   1   7   1  12   0
999975   4   3   2   7   3  10   1  12   4   1   0
999976   2   8   2  11   1   6   2   7   4  11   1
999977   3  13   2   3   1   4   2   1   3   1   1
999978   3   1   2   8   1   4   4  10   3   3   0
999979   3   3   2  12   4   2   3  13   1   9   0
999980   2  10   3  10   2   9   3  11   4  13   1
999981   3   5   1   2   2   1   2   9   2   8   0
999982   1   1   3   1   1  11   2   3   2   6   1
999983   2   5   4   7   1  11   4   6   3   5   1
999984   4   6   4   3   1   4   2   7   1   2   0
999985   1  11   1  13   2   6   3   6   2   1   1
999986   2   8   4  10   3   6   2   4   3   3   0
999987   1   8   4   9   3   1   1   1   2   8   2
999988   4   3   4   7   3   6   4  12   1   1   0
999989   1  11   3  13   2  13   4   3   3  10   1
999990   2  12   4   3   1   3   3   5   3   2   1
999991   1   4   4   8   4   5   3   9   2   1   0
999992   1   9   3   6   2   8   3   5   2   9   1
999993   1  12   3   9   3   6   1   3   1   9   1
999994   3   7   1   6   4  12   2   1   1   4   0
999995   3   1   1  12   2   9   4   9   2   6   1
999996   3   3   4   5   2   7   1   4   4   3   1
999997   1  11   4   7   3   9   1  13   2   7   1
999998   3  11   1   8   1   1   3  13   2   8   1
999999   2   5   2   9   4   9   2   3   3   3   2

[1000000 rows x 11 columns]

In [6]:
X_train = np.array(train.drop([10],1))
y_train= np.array(train[10])
X_test = np.array(test.drop([10],1))
y_test= np.array(test[10])

In [7]:
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn import metrics

In [19]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print metrics.accuracy_score(y_test,y_pred)

0.552178

In [18]:
rr=RandomForestClassifier(5,oob_score=True,n_jobs=-1,random_state=29)
rr.fit(X_train,y_train)
y_pred2=rr.predict(X_test)
print metrics.accuracy_score(y_test,y_pred2)

0.531786

In [10]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred4 = gnb.predict(X_test)
print metrics.accuracy_score(y_test,y_pred4)

0.501209

In [11]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred5 = logreg.predict(X_test)
print metrics.accuracy_score(y_test,y_pred5)

0.501209

In [12]:
adc = AdaBoostClassifier()
adc.fit(X_train,y_train)
y_pred6 = adc.predict(X_test)
print metrics.accuracy_score(y_test,y_pred6)

0.491576

In [13]:
clf = SGDClassifier(loss="hinge", penalty="l2")
clf.fit(X_train,y_train)
y_pred7 = clf.predict(X_test)
print metrics.accuracy_score(y_test,y_pred7)

0.425496

In [14]:
tc = DecisionTreeClassifier()
tc.fit(X_train,y_train)
y_pred8 = tc.predict(X_test)
print metrics.accuracy_score(y_test,y_pred8)

0.479096

In [ ]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train,y_train)
y_pred3 = clf.predict(X_test)
print metrics.accuracy_score(y_test,y_pred3)