In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table('C:/Users/Bhavya Popli/Desktop/datasets/Skin_NonSkin.txt', header=None)
df.head()

    0   1    2  3
0  74  85  123  1
1  73  84  122  1
2  72  83  121  1
3  70  81  119  1
4  70  81  119  1

In [3]:
df.dropna()

          0    1    2  3
0        74   85  123  1
1        73   84  122  1
2        72   83  121  1
3        70   81  119  1
4        70   81  119  1
5        69   80  118  1
6        70   81  119  1
7        70   81  119  1
8        76   87  125  1
9        76   87  125  1
10       77   88  126  1
11       77   88  126  1
12       77   88  126  1
13       78   89  127  1
14       77   85  125  1
15       78   86  126  1
16       78   86  126  1
17       77   85  125  1
18       76   84  124  1
19       77   85  125  1
20       80   88  128  1
21       83   91  131  1
22       83   91  131  1
23       84   92  132  1
24       84   92  132  1
25       83   91  131  1
26       80   88  128  1
27       78   86  126  1
28       78   86  126  1
29       79   87  127  1
...     ...  ...  ... ..
245027  162  161  110  2
245028  162  161  110  2
245029  162  161  110  2
245030  162  161  110  2
245031  162  161  110  2
245032  162  161  110  2
245033  165  164  113  2
245034  165  164  113  2
245035  165  164  113  2
245036  165  164  113  2
245037  165  164  113  2
245038  164  163  112  2
245039  164  163  112  2
245040  164  163  112  2
245041  163  162  112  2
245042  163  162  112  2
245043  163  162  112  2
245044  163  162  112  2
245045  163  162  112  2
245046  163  162  112  2
245047  163  162  112  2
245048  163  162  112  2
245049  163  162  112  2
245050  163  162  112  2
245051  163  162  112  2
245052  163  162  112  2
245053  163  162  112  2
245054  163  162  112  2
245055  163  162  112  2
245056  255  255  255  2

[245057 rows x 4 columns]

In [4]:
X = np.array(df.drop([3],1))
y = np.array(df[3])

In [5]:
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4)

In [7]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
from sklearn import metrics
print metrics.accuracy_score(y_test,y_pred)

0.999316486947

In [8]:
rr=RandomForestClassifier(150,oob_score=True,n_jobs=-1,random_state=29)
rr.fit(X_train,y_train)
y_pred2=rr.predict(X_test)
print metrics.accuracy_score(y_test,y_pred2)

0.999408302133

In [ ]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train,y_train)
y_pred3 = clf.predict(X_test)
print metrics.accuracy_score(y_test,y_pred3)

In [9]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred4 = gnb.predict(X_test)
print metrics.accuracy_score(y_test,y_pred4)

0.923885210614

In [10]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred5 = logreg.predict(X_test)
print metrics.accuracy_score(y_test,y_pred5)

0.917958030258

In [11]:
adc = AdaBoostClassifier()
adc.fit(X_train,y_train)
y_pred6 = adc.predict(X_test)
print metrics.accuracy_score(y_test,y_pred6)

0.952521347031

In [12]:
clf = SGDClassifier(loss="hinge", penalty="l2")
clf.fit(X_train,y_train)
y_pred7 = clf.predict(X_test)
print metrics.accuracy_score(y_test,y_pred7)

0.919396468176

In [13]:
tc = DecisionTreeClassifier()
tc.fit(X_train,y_train)
y_pred8 = tc.predict(X_test)
print metrics.accuracy_score(y_test,y_pred8)

0.999132856574